name       : mono-basic
version    : 4.6
release    : 2
source     :
    - https://github.com/mono/mono-basic/archive/4.6.tar.gz : 8d6ce42a186d812c0e62af035d23fad524378fad78f9df5689e5591928d415ad
license    :
    - LGPL-2.0
    - MIT
component  : programming.library
summary    : Mono Basic Runtime and Compiler
description: |
    Mono Basic is an open source implementation of Microsoft's Visual Basic Programming language and runtime that runs atop the (Mono) .NET Framework
builddeps  :
    - mono-devel
rundeps    :
    - mono
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
