name       : mono-basic
version    : 4.7
release    : 4
source     :
    - https://github.com/mono/mono-basic/archive/4.7.tar.gz : fb3d5e2171a0fb4555022712d0cdcce72af7c07c7e4861b1440b2e33e01edd5d
license    :
    - LGPL-2.0-or-later
    - MIT
component  : programming.tools
summary    : Mono Basic Runtime and Compiler
description: |
    Mono Basic is an open source implementation of Microsoft's Visual Basic Programming language and runtime that runs atop the (Mono) .NET Framework
builddeps  :
    - pkgconfig(mono)
rundeps    :
    - mono
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
